---

all:
  vars:
    ansible_user: ubuntu
    serviio_version: 2.1 # ダウンロードファイル名、実行ファイルパス、.serviceファイル中などで使用

    dlna_friendly_name: "Apple TV 4K (via serviio)"

  hosts:
    serviio:
      ansible_host: 192.168.206.25
# NTPサーバアドレス
      ntp_address: "ntp.jst.mfeed.ad.jp ntp.nict.jp"
